name: Notify Parent Repo on Submodule Push
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }} 
          repository: PWNight/FoxWorldWeb
          event-type: submodule-updated
